filebeat.prospectors:

- input_type: log
  paths:
    - '/mnt/log/*.log'
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml

output.logstash:
  hosts: ["logstash:5000"]
  index: filebeat-myapp
