version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
      #    volumes:
      # - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      #    volumes:
            #      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
            #      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    environment:
      - "LS_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      #    volumes:
            #      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat:
    build:
      context: filebeat/
      #    volumes:
            #      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
    ports:
      - "5601:5601"
    networks:
      - elk
      - logs
    depends_on:
      - elasticsearch

  myapp:
    build:
      context: myapp/
    ports:
      - "8080:80"
    networks:
      - logs


networks:
  elk:
    driver: bridge
  logs:
    driver: bridge
