#=========================== Filebeat prospectors =============================

filebeat.prospectors:

- input_type: log
  paths:
    - '/log/*.log'

#================================ Outputs ======================================

#----------------------------- Logstash output ---------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["localhost:5000"]
  index: filebeat-myapp

#================================ Logging =====================================

# Sets log level. The default log level is info.
# Available log levels are: critical, error, warning, info, debug
logging.level: info

# At debug level, you can selectively enable logging only for some components.
# To enable all selectors use ["*"]. Examples of other selectors are "beat",
# "publish", "service".
#logging.selectors: ["*"]

# Logging to rotating files files. Set logging.to_files to false to disable logging to
# files.
logging.to_files: true
logging.files:
    # Configure the path where the logs are written. The default is the logs directory
    # under the home path (the binary location).
    #path: #{filebeat-logging-file}

    # The name of the files where the logs are written to.
    name: "filebeat-myapp"

    # Configure log file size limit. If limit is reached, log file will be
    # automatically rotated
    rotateeverybytes: 10485760 # = 10MB

    # Number of rotated log files to keep. Oldest files will be deleted first.
    keepfiles: 7

